[profile.default]
src = "."
out = "out"
libs = ["lib"]
test = "test"

# Solidity version (latest)
solc_version = "0.8.28"

# Optimizer settings
optimizer = true
optimizer_runs = 200
via_ir = true

# EVM version
evm_version = "shanghai"

# Gas limit for tests
gas_limit = 30_000_000

# Remappings
remappings = [
    "forge-std/=lib/forge-std/src/"
]

# Enable FFI for advanced testing
ffi = false
fs_permissions = [
    { access = "read-write", path = "./test-results/" }
]